sudo: required

language: cpp

compiler:
  - gcc
  - clang

arch:
  packages:
    - cpprestsdk-git
  script:
    - "git submodule init"
    - "git submodule update"
    - "cmake -DCMAKE_BUILD_TYPE=Release"
    - "sudo make install"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
